---
title: "Data Import"
output: github_document
---

```{r setup}
library(tidyverse)
library(readxl)
library(haven)
```

## Read some data

Read in the litters dataset.

```{r}
litters_df = read_csv('./data/FAS_litters.csv')
litters_df = janitor::clean_names(litters_df)
# reason why don't load the package with library() is that this is the only function we're gonna use in this package.
```

## Take a look at the data

Printing in the console

```{r}
litters_df
```

```{r}
head(litters_df)
# give the first 6 rows of the dataframe
tail(litters_df)
# give the last 6 rows of the df
```

```{r}
skimr::skim(litters_df)
```

view(litters_df) should be used in console directly


## Options to read CSV

Check out `?read_csv` for more information
```{r}
litters_df = read_csv('./data/FAS_litters.csv', skip = 10, col_names = FALSE)
# skip the first 10 rows

litters_df = read_csv('./data/FAS_litters.csv', na = c("", ".", "NA", "999"))

litters_df = read_csv('./data/FAS_litters.csv')

```


## Other file formats

read in an excel file:

```{r}
mlb_df = read_excel('data/mlb11.xlsx', range = 'A1:F7')
mlb_df
```

read in a SAS file:

```{r}
pulse_df = read_sas('./data/public_pulse_data.sas7bdat')
```


## comparison with Base R

Why don't we use `read.csv`?

```{r}
litters_base = read.csv('./data/FAS_litters.csv')
litters_readr = read_csv('./data/FAS_litters.csv')

litters_base
litters_base
# always use read_csv
```


## exporting data

export the mlb sub-table.

```{r}
write_csv(mlb_df, './data/mlb_subtable.csv')
```




